services:
  - type: web
    name: bluevitatech-api
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm run server:dev
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
    autoDeploy: true
    branch: main
